### ISSUE TITLE
No Video and Audio 

### ISSUE THREAD

**Issue by mchatoo** [eintamil/repository.eintamil#11]
I just installed the Einthusan from EinTamil and am able to search for movies (finally!!) without error codes. The movies appear to be playing but there is no video and no audio. I can see the movie timer along the bottom showing the movie progressing but nothing else. I had to use OpenSubtitles to get subtitles to show but no video/audio. What am I doing wrong here please? I am a novice at this stuff and I really want to get Einthusan up and running again for us. Please help... Thanks so much

**Comment by eintamil** [comment]
Thats very weird. Could you please share me info like - what is the kodi version, what device you are using, etc. Also, does other video add-ons play fine?

**Comment by mchatoo** [comment]
So sorry ... I thought only Einthusan was affected but I was wrong. It was my Kodi settings I needed to fix. I am sorry to waste your time. Thanks so much! Einthusan works great!
