### ISSUE TITLE
Unable to install on Kodi 19

### ISSUE THREAD

**Issue by sathish804** [eintamil/repository.eintamil#16]
Hi,

When tried to install the 3.x addon on Kodi 19 giving dependency error. 

Please update the addon.

**Comment by eintamil** [comment]
Hi, I will try to reproduce this error and solve it at the earliest.
Could you please share the below details to help me understand the issue:
a) What is your Kodi version?
b) What device are you using?
c) Error message or screenshot of kodi.log

**Comment by sathish804** [comment]
> Hi, I will try to reproduce this error and solve it at the earliest.
> Could you please share the below details to help me understand the issue:
> a) What is your Kodi version?
> b) What device are you using?
> c) Error message or screenshot of kodi.log

Hi, 

Please find the information. 
a. Kodi version 19 Rc1
b. Oneplus 6t
c. Log.. https://controlc.com/3f072727
![Screenshot_20210122-173405](https://user-images.githubusercontent.com/14090242/105518687-df102280-5cd8-11eb-8ff4-941ffab2aca6.jpg)

**Comment by eintamil** [comment]
Hello, Please try the latest version of the addon and revert if the issue still exists.

**Comment by sathish804** [comment]
> Hello, Please try the latest version of the addon and revert if the issue still exists.

Tested it now its installed but the addon logo is missing. 
![Uploading Screenshot_20210202-114152.jpg…]()

**Comment by eintamil** [comment]
Yes, I am aware of it. May be, the image needs to be resized or renamed. I will research and push in next version.
I believe, the core issue is now resolved?

**Comment by sathish804** [comment]
> Yes, I am aware of it. May be, the image needs to be resized or renamed. I will research and push in next version.
> I believe, the core issue is now resolved?

Yes core issue is solved now.
