### ISSUE TITLE
Ver3 Add not working in Kodi 19

### ISSUE THREAD

**Issue by raamch** [eintamil/repository.eintamil#19]
Hi I am on Kodi 19 stable one. I have installed eintamil repo and installed eitusan3 add-on. But the add-on is not working and fail to launch even. Plz check.

**Comment by eintamil** [comment]
Hi, Please let me know the below details:
- Kodi version
- Device type
- Error message from kodi.log
- Error screenshot

**Comment by raamch** [comment]
Hi


   - Kodi version: Kodi 19.0, eithusan v3
   - Device type: fire stick
   - Error message from kodi.log:  einthusan error. Error GetDirectory-
   error getting plugin://plugin.video.einthusan3/

**Comment by raamch** [comment]
Kodi version: Kodi 19.0, eithusan v3
Device type: fire stick
Error message from kodi.log:  einthusan error. Error GetDirectory- error getting plugin://plugin.video.einthusan3/

**Comment by eintamil** [comment]
I am afraid, this error message doesn't help me much and I do not have firestick to replicate this issue. 
Is all the dependencies installed? 
Please ensure you are installing the latest version of Einthusan 3.0.10
Also, please update Kodi to the latest version available.

**Comment by raamch** [comment]
Hi,

Kodi is most updated version and Einthusan is 3. No error was showed while
installing so all dependacies are installed correctly. Plugin fail to open.

**Comment by raamch** [comment]
Log file is uploaded to https://paste.kodi.tv/pupeekumaji

**Comment by eintamil** [comment]
Ram, Unfortunately, I am unable to find the error message "Error GetDirectory-error getting plugin://plugin.video.einthusan3/" in the log file link you shared. Could you please share the correct file.

Also, note the timestamp when you open einthusan addon and when it crashes.

**Comment by Dineshkumar-Ponnusamy** [comment]
I think, I found the error, it's an index error. 

Error Type: <class 'IndexError'>
Error Contents: list index out of range

main.py Line 628, function_map[mode](name, url, language, mode)
main.py Line 279, list_vides(url, "results")
main.py Line 285, if video_list[-1][6] != "":

**Comment by eintamil** [comment]
Is this issue still exists? Can this be closed?
