### ISSUE TITLE
Getting errors for UHD videos though I am premium user and login credentails are correct in the Einthusan addon.

### ISSUE THREAD

**Issue by veerapursandesh** [eintamil/repository.eintamil#20]
I am using Amazon firestick device for streaming. 

Kodi Version: 19.1
Einthusan Repo Version: Ein Tamil 1.0.0
Einthusan App Version: Ein Tamil 3.0.10

Attached screenshots will provide more details.

<img width="1440" alt="Screen Shot 2021-05-29 at 4 54 07 PM" src="https://user-images.githubusercontent.com/5890384/120087673-ceb0ef80-c09e-11eb-9766-303b1f577a2f.png">
<img width="1440" alt="Screen Shot 2021-05-29 at 4 54 19 PM" src="https://user-images.githubusercontent.com/5890384/120087674-d2dd0d00-c09e-11eb-8bd3-f751c7fb72c7.png">

**Comment by eintamil** [comment]
Issue Fixed in v3.0.11. Please update the addon and revert if the issue still exists.
