### ISSUE TITLE
Getting the error "Please add premium membership login details" on 3.11 version of the addon

### ISSUE THREAD

**Issue by veerapursandesh** [eintamil/repository.eintamil#21]
I am using Amazon firestick device for streaming.

Kodi Version: 19.1
Einthusan Repo Version: Ein Tamil 1.0.0
Einthusan App Version: Ein Tamil 3.0.11

I have provided the login as shown below but still getting the error message when attempt made to stream Ultra  HD videos. 

<img width="589" alt="Screen Shot 2021-06-03 at 10 48 06 AM" src="https://user-images.githubusercontent.com/5890384/120689708-3e392d00-c459-11eb-8f33-d08aee66b53c.png">
<img width="587" alt="Screen Shot 2021-06-03 at 10 48 22 AM" src="https://user-images.githubusercontent.com/5890384/120689711-3ed1c380-c459-11eb-8021-a5093281fa04.png">

**Comment by eintamil** [comment]
Unfortunately, I do not have a premium membership to test this. Could you uninstall the add-on and install a fresh one and let me know if the issue still exists.

**Comment by veerapursandesh** [comment]
I still see the same problem as earlier. Has anyone else seen this issue?

**Comment by eintamil** [comment]
Hi, Are you able to login fine online in your laptop and what an UHD movie fine with the premium account?

**Comment by veerapursandesh** [comment]
I have tried on with Kodi app Firestick, Apple TV and my MacBook but I see the same error as mentioned.

However, if I access the Einthusan website directly in the browser of my laptop, I can watch the UHD videos with my credentials.

**Comment by eintamil** [comment]
Please share the Kodi.log file

**Comment by veerapursandesh** [comment]
![IMG_0006](https://user-images.githubusercontent.com/5890384/125725912-4e5e0452-bc37-4e9b-be98-b91f9c2750e7.JPG)
![IMG_0007](https://user-images.githubusercontent.com/5890384/125725926-2d59faf8-b0af-460a-a09f-3b82913c81ae.JPG)
![IMG_0008](https://user-images.githubusercontent.com/5890384/125725934-1ccd843f-aa7a-4e81-83bb-bf2bb279c382.JPG)
![IMG_0009](https://user-images.githubusercontent.com/5890384/125725943-a5ddc22d-8c37-4056-963f-3e823ba6691c.JPG)


Do note that I don't see these errors when I login to the EInthusan account on my laptop and access UHD videos. It's only seen when I access Einthusan in Kodi and while accessing UHD videos.

**Comment by eintamil** [comment]
Hello, Do you have any special characters in your password? Could you please temporarily reset your password to a simple one and let me know if that works fine.

**Comment by veerapursandesh** [comment]
I just have a "." and alphabets in my password. I don't see an option change password in Einthusan. Would this info be helpful in debugging?

**Comment by eintamil** [comment]
Ok. I will try to recreate this scenario. 
In the meanwhile, could you update the password using any of the below options and confirm if it works fine:
https://einthusan.tv/forgot-password/?lang=tamil
https://einthusan.tv/account/?lang=tamil

**Comment by veerapursandesh** [comment]
I tried with a different password that has only letters and numbers and still I see the same error as shown in logs.

**Comment by Allwaysmrright** [comment]
hi..did you guys find a solution for this issue...can any one help i facing same problem
