### ISSUE TITLE
Einthusan3 on kodi 19.1 

### ISSUE THREAD

**Issue by arivudainambik** [eintamil/repository.eintamil#25]
I am getting error like “please check and update the base URL in Addon settings and restart the addon”

device : android 9 tv

kodi 19.1

eintamil einthusan3

**Comment by eintamil** [comment]
Hi, please uninstall the add-on and it's data. Reinstall and try again.
Also, check there is no records in your hosts file. Please check add-on
settings in Expert mode and verify the Base_URL field value or reset it to
default. Please attach the screenshot.

**Comment by eintamil** [comment]
Hello, Is this issue resolved. If yes, please close this ticket.
