### ISSUE TITLE
Buffering Issues - Video Resolution option

### ISSUE THREAD

**Issue by raaz899** [eintamil/repository.eintamil#26]
Can the next update have options for 480 or 360 video resolutions?

Most videos which is on default- 720 keep buffering a lot and on settings, there is no option for flexibility to change this as default it's always 720 or 4k.

We love the app and hat off to the developers!

Appreciate if this function can be added on the next release, please?   Its something minor and I'm sure the developers can add this option on EINTAMIL configuration settings

Others please vote for this case would appreciate it.

Thanks

**Comment by eintamil** [comment]
Hello, This is not an official addon or directly to actual einthusan website. 
Because the einthusan website does not offer videos in different resolutions, this addon will be unable to implement the same.
