### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by buddingdoc** [eintamil/repository.eintamil#3]
I have Kodi 18.6 and I installed version 2.0 from the repository. But it says you need a premium account or to wait when I try to play any movie. But even if I wait 10 minutes, it does not load. Thank you.

**Comment by eintamil** [comment]
Recently einthusan has placed cap on non-premium usage, esp over Friday nights and Weekends.
I am working on some alternate solution to handle this. 
Do you have the same problem on weekdays or mornings?
In the meanwhile, one solution which mostly works for me is, restart kodi and then play the movie.
Let me know if it works for you too.

**Comment by eintamil** [comment]
> I have Kodi 18.6 and I installed version 2.0 from the repository. But it says you need a premium account or to wait when I try to play any movie. But even if I wait 10 minutes, it does not load. Thank you.

Implemented retry logic in v2.0.5 which should handle this issue.
Uninstall older version (clear user data) and install to latest version.
If any issues, raise at https://github.com/eintamil/repository.eintamil/issues
