### ISSUE TITLE
IndexError: list index out of range on kodi

### ISSUE THREAD

**Issue by sange9402** [eintamil/repository.eintamil#32]
Hello,

Doesn't work on Kodi but works on site. Please fix on kodi

IndexError: list index out of range

**Comment by sange9402** [comment]
Hi it works now just had to restart my whole firestick. Does the login work?

Thanks,
Sanny

**Comment by eintamil** [comment]
Please try the below steps and comment if you are still facing the issue:
```
- Kindly uninstall the older version of the Einthusan addon
- Update to EinTamil Kodi Repository Version 1.1.0
- Install Einthusan addon Version 3.1.0
```
