### ISSUE TITLE
EinTamil not working??

### ISSUE THREAD

**Issue by rnanjun** [eintamil/repository.eintamil#33]
EinTamil was working 2 weeks ago and not it is working. Anyone else have the same problem??

**Comment by eintamil** [comment]
Hello, Could you please attach screenshots or error message from log file?

**Comment by Karny13** [comment]
I tried it today and it just keeps loading after the installation when i click on the Enthusian addon.

**Comment by Harry9838** [comment]
> I tried it today and it just keeps loading after the installation when i click on the Enthusian addon.
> 
> Error is: Please check and update the Base URL in Addon Settings and restart the addon.

same error with kodi 21.0 plz help

**Comment by eintamil** [comment]
Please try the below steps and comment if you are still facing the issue:
```
- Kindly uninstall the older version of the Einthusan addon
- Update to EinTamil Kodi Repository Version 1.1.0
- Install Einthusan addon Version 3.1.0
```
