### ISSUE TITLE
Eintamil not working at specific times when server busy 

### ISSUE THREAD

**Issue by bkchn** [eintamil/repository.eintamil#38]
Eintamil not working at specific times of the day

GMT times around 6 pm to 12 midnight when the einthusan servers are busy.
To check further we tried opening the same movie directly on einthusan.tv in browser. When we access the site einthusan.tv site during the same time to open a movie we are getting server busy message and also a message is displayed that the request is  added to waitlist queue (screenshot below) and after a minute or two it refreshes automatically and the movie opens.
But this is not handled in this add-on so it throws error as cannot open ,check logs and doesn't open the movie .
Either a more timeout or configurable settings should be given in the add-on internals when it tries to open a movie and it cannot open it . 
Can the developer check this?
I can post more details if you require further information.

<img width="960" alt="queuewait" src="https://github.com/eintamil/repository.eintamil/assets/44496437/a6ef8bca-0408-4aff-b40b-b4859ecc69f5">

**Comment by eintamil** [comment]
Please try the below steps and comment if you are still facing the issue:
```
- Kindly uninstall the older version of the Einthusan addon
- Update to EinTamil Kodi Repository Version 1.1.0
- Install Einthusan addon Version 3.1.0
```
