### ISSUE TITLE
Kodi 21 in firestick gives error when opening einthusan

### ISSUE THREAD

**Issue by anguraj82** [eintamil/repository.eintamil#40]
Installed einthusan 3.x version in kodi 21 omega(firestick apk). When I open addon and click Tamil movies/featured it shows error to update base url in settings. The base url is correctly showing as https://einthusan.tv but keep getting this error. The same url works in kodi 20.1

**Comment by eintamil** [comment]
Please try the below steps and comment if you are still facing the issue:
```
- Kindly uninstall the older version of the Einthusan addon
- Update to EinTamil Kodi Repository Version 1.1.0
- Install Einthusan addon Version 3.1.0
```
