### ISSUE TITLE
Error with Einthusan

### ISSUE THREAD

**Issue by rnanjun** [eintamil/repository.eintamil#41]
Keep getting the following error when launching Einthusan

Please check and update the Base URL in Addon Settings and restart the addon.

**Comment by eintamil** [comment]
Please try the below steps and comment if you are still facing the issue:
```
- Kindly uninstall the older version of the Einthusan addon
- Update to EinTamil Kodi Repository Version 1.1.0
- Install Einthusan addon Version 3.1.0
```
