### ISSUE TITLE
Video not playing. "Is it taking too long?" message. 

### ISSUE THREAD

**Issue by Kyay12** [eintamil/repository.eintamil#42]
![Screenshot 2024-09-20 at 08-34-03 PGMovieClipWatcher - Einthusan](https://github.com/user-attachments/assets/7f284b48-18b7-425e-9288-e9201ee848d0)

None of the videos are playing. I always get this message without the video playing: "Is it taking too long? Click here to run a speed test." Please help as soon as possible.

**Comment by eintamil** [comment]
Please submit issue using "Contact" link at the bottom of the website.
