### ISSUE TITLE
Playback failed

### ISSUE THREAD

**Issue by Fishyboiyea1** [eintamil/repository.eintamil#43]
When I click any movie it sais 'Einthusan error' and also 'Check the log for more info'. It sais in a pop up that the playback failed and that one or more items failed to and to check the log for more information about this error.

**Comment by hamid1135** [comment]
the same thing happens to me

**Comment by bkchn** [comment]
Related to issue#38

**Comment by Fishyboiyea1** [comment]
resolved, thanks

**Comment by bkchn** [comment]
Check it on peak traffic time and different time of the day if it is resolved or not

**Comment by shankarke** [comment]
It does not work for me and fails with check log file error.

Can you please fix this?

**Comment by eintamil** [comment]
Please try the below steps and comment if you are still facing the issue:
```
- Kindly uninstall the older version of the Einthusan addon
- Update to EinTamil Kodi Repository Version 1.1.0
- Install Einthusan addon Version 3.1.0
```
