### ISSUE TITLE
Einthusan addon not working in kodi 21.x.x 

### ISSUE THREAD

**Issue by RyderLas** [eintamil/repository.eintamil#45]
Einthusan add-on not working in kodi 21.x.x, Any fix for it??

**Comment by eintamil** [comment]
Please try the below steps and comment if you are still facing the issue:
```
- Kindly uninstall the older version of the Einthusan addon
- Update to EinTamil Kodi Repository Version 1.1.0
- Install Einthusan addon Version 3.1.0
```

**Comment by RyderLas** [comment]
Nice…Now the movie plays only on default addon settings without login , but if we give login it has the playback issue.

**Comment by eintamil** [comment]
Please uninstall the addon (also remove addon data). 
Restart the device and install the addon. 
If the issue still exists, please post the log file.

**Comment by eintamil** [comment]
Is your login a premium user account or regular account?
