### ISSUE TITLE
Eintamil addon not opening

### ISSUE THREAD

**Issue by bkgit9** [eintamil/repository.eintamil#5]
Eintamil addon not opening  from today.The folder "Recently added" is not opening inside the addon.Continuously loading.

**Comment by bkgit9** [comment]
> 
> 
> Eintamil addon not opening from today.The folders are not opening inside the addon.Continuously loading.

It happens when opening the Recently Added folder

**Comment by eintamil** [comment]
Error with "Tamil > Recently Added" is now fixed. 
Please try latest (x.0.6) version and comment if the issue still exists.
