### ISSUE TITLE
Kodi Force closing

### ISSUE THREAD

**Issue by KodyBuilding** [eintamil/repository.eintamil#7]
Hi Eintamil,

I cannot thank you enough for updating the Einthusan addon. Great job.

![Screenshot_20200412-150705_Kodi](https://user-images.githubusercontent.com/52407759/79065666-c72e5b80-7ccf-11ea-866b-153adf9d169c.jpg)

I've installed the addon according to the instructions. But when I click on a movie it force closes the Kodi. Using Kodi 18.6 on Android phone.

**Comment by eintamil** [comment]
Hello, Thanks for the feedback. 

I haven't tested it on Android Phone. 

At first glance on the log screenshot, it looks like the addon has done it's part and the cause for crash could be something else.

A couple of questions:
- What is the android version ?
- Does any other kodi video (m3u8) addon play fine ?
- Is this related to this issue - https://github.com/xbmc/xbmc/issues/17120 and https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/264 ?
-

**Comment by eintamil** [comment]
Hello, Thanks for the feedback. 

I haven't tested it on Android Phone. 

At first glance on the log screenshot, it looks like the addon has done it's part and the cause for crash could be something else.

A couple of questions:
- What is the android version ?
- Does any other kodi video (m3u8) addon play fine ?
- Is this related to this issue - https://github.com/xbmc/xbmc/issues/17120 and https://github.com/Catch-up-TV-and-More/plugin.video.catchuptvandmore/issues/264 ?

**Comment by KodyBuilding** [comment]
Hi
Thanks for your response. 

I am using Samsung S9, Android 10. 
I am using many other addons and don't have such issue. For example I use Movierulz (Deccan delight addon) and the movies work fine but when I play Einthusan it force closes the Kodi when it tries to play the movie. I didn't have this issue in the old Enthisan addon. Hope you can look into this and find us fix for this please.

Thank you.
